CREATE TABLE dim_Indicators(
    IndicatorKey INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    IndicatorID INT,
    IndicatorName VARCHAR(30),
    MeasureUnits VARCHAR(20),
    Frequency VARCHAR(20),
    Category VARCHAR(20),
    FromDate DATE,
    ToDate DATE,
    IsCurrent VARCHAR(3));
    
CREATE TABLE fact_Indicators(
    RecordID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    IndicatorKey INT NOT NULL,
    IndicatorID INT NOT NULL,
    FromDate DATE,
    ToDate DATE,
    IndicatorValue NUMERIC(14, 2));
    
ALTER TABLE fact_Indicators 
    ADD FOREIGN KEY(IndicatorKey) REFERENCES dim_Indicators(IndicatorKey);

-- mediator table
CREATE TABLE dim_IndicatorsOld(
  	IndicatorKey INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    IndicatorID INT NOT NULL,
    IndicatorName VARCHAR(30),
    MeasureUnits VARCHAR(20),
    Frequency VARCHAR(20),
    Category VARCHAR(20),
    FromDate DATE,
    ToDate DATE,
    IsCurrent VARCHAR(3));


    
